require 'rake'
require 'rake/testtask'

desc 'Default: run unit tests'
task :default => :test

desc 'Run unit tests'
Rake::TestTask.new(:test) do |t|
   t.libs << 'app'
   t.pattern = 'test/**/test_*.rb'
   t.verbose = true
end
